# Generated by Django 2.2 on 2019-11-02 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_auto_20191010_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(verbose_name='Дата начала работы')),
                ('finished_at', models.DateField(verbose_name='Дата окончания работы')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='webapp.Project', verbose_name='Проект')),
            ],
        ),
    ]
