# Generated by Django 2.2 on 2019-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20191105_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
