# Generated by Django 2.2 on 2019-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191113_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='started_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала работы'),
        ),
    ]
